restservices:
  build: rest-services
  ports:
    - "8080:8080"
  links:
    - wiremock
    - mongodb

wiremock:
  build: integrationmock
  ports:
    - "18080:8080"
  volumes:
    - ./mockdata/:/wiremock/mappings/

mongodb:
  build: mongodb
  ports:
    - "27017"
  volumes:
    - ./data/mongo:/data/db


editor:
  build: mockdata-web
  ports:
    - "80:80"
  links:
    - restservices
  volumes:
    - ./mockdata-editor/:/src