restservices:
  build: rest-services
  ports:
    - "80:8080"
  links:
    - wiremock
    - mongodb

wiremock:
  build: integrationmock
  ports:
    - "18080:8080"
  volumes:
    - ./mockdata/:/wiremock/mappings/

mongodb:
  build: mongodb
  ports:
    - "27017"
  volumes:
    - ./data/mongo:/data/db
