restservices:
  build: rest-services
  ports:
    - "8080:8080"
  links:
    - wiremock
    - mongodb

wiremock:
  build: integrationmock
  ports:
    - "18080:8080"
  volumes:
    - ./mockdata/:/wiremock/mappings/

mongodb:
  build: mongodb
  ports:
    - "27017"
  volumes:
    - ./data/mongo:/data/db


editor:
  build: mockdata-editor
  ports:
    - "80:80"
  links:
    - restservices
  volumes:
    - ./mockdata-editor/:/src


 #docker run --name <frontend_server_name> -v <path_of_angualrjs_project>:/opt/angular
 # --link <backend_server_name>:apiserver
#  -P -d billlee/nginx-angular-devel