restservices:
  build: rest-services
  ports:
    - "8080:8080"
  links:
    - wiremock
    - mongo

wiremock:
  build: integrationmock
  ports:
    - "18080:8080"
  volumes:
    - ./mockdata/:/wiremock/mappings/

mongo:
  build: mongodb
  ports:
    - "27017"
  volumes:
    - ./mongodb/data:/data/db