restservices:
  build: rest-services
  ports:
    - "8080:8080"
  links:
    - wiremock

wiremock:
  build: integrationmock
  ports:
    - "18080:8080"
  volumes:
    - ./mockdata/:/wiremock/mappings/

